# Generated by Django 4.2 on 2023-10-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portafolio", "0004_remove_projecto_fecha_envio_contacto_fecha_envio"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecto",
            name="explicacion",
            field=models.CharField(default="", max_length=600),
        ),
    ]
